name: Checks

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        pip install --user 'click<8.0.0'
        pip install --user covimerage==0.2.1

    - name: Run tests
      shell: bash
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        ./run_tests.sh --profile

    - name: Generate coverage report
      run: |
        set -eo pipefail
        profile_file=$(ls | grep 'profile_file.*0\.4\.3')
        python -m covimerage write_coverage ${profile_file}
        sed -i "s,/testplugin/,$PWD/,g" .coverage_covimerage
        python -m covimerage -vv xml
        python -m covimerage report -m

    - name: Upload coverage report
      uses: codecov/codecov-action@v2.1.0
      with:
        fail_ci_if_error: true
        verbose: true
